package com.hadleexception;

import java.util.Scanner;

public class Multiexptions_Thrws {

	public static void main(String[] args) {
      
		try {
			m1();
		} catch (Exception e) {
			System.out.println(e.getMessage());
			
		}
	}
	public static void m1() throws ArithmeticException,NullPointerException,StringIndexOutOfBoundsException{
		
		Scanner sc = new Scanner(System.in);
		System.out.println("Enter the number");
		int a=sc.nextInt();
		System.out.println(10/a);
		String s=null;
		
		System.out.println(s.charAt(2));
		System.out.println(s.length());
	}
	{
		
	}

}
